fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.0
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]