# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pr: none
trigger:
  branches:
    include:
    - '*'

stages:
- stage: static_checks
  displayName: Static Checks
  dependsOn: []
  jobs:
    - job:
      displayName: "Check Git Tags"
      steps:
      - script: echo "##vso[build.addbuildtag]Automated"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

- stage: test_and_build
  displayName: 'Test and build'
  dependsOn: []
  jobs:
    - job:
      displayName: ' '
      strategy:
        matrix:
          python36:
            PYTHON_VERSION: '3.6'
          python37:
            PYTHON_VERSION: '3.7'
          python38:
            PYTHON_VERSION: '3.8'
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: $(PYTHON_VERSION)
        - script: |
            pip install -U pip
            pip install -U -r requirements.txt
          displayName: 'Install requirements'
        - script: |
            pip install pytest-azurepipelines
            pytest --cov=client --junitxml=testResults.xml
          displayName: 'Tests'
        - bash: |
            pip install -U pip codecov
            report_name="ubuntu18-04_$(PYTHON_VERSION)"
            python -m codecov --token $(CODECOV_TOKEN) \
              --file coverage.xml \
              -n ${report_name}
          displayName: 'Send coverage to codecov'
          condition: succeededOrFailed()
